version: "3.7"

services:
  web:
    image: nginx
    container_name: simple-nginx-container
    # ports: # ポートの指定はnginx-proxyでするのでここではしない
    #   - "80:80"
    networks:
      - container-link
    volumes:
      - ./src/public:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=hideri.net # nginx-proxyのホスト設定 ※example.comを書き換えてください
      - LETSENCRYPT_HOST=hideri.net # Let's Encryptのホスト設定 ※example.comを書き換えてください
      - LETSENCRYPT_EMAIL=hori.hide1003@gmail.com # Let's Encryptのメール設定
      - LETSENCRYPT_TEST=false # Let's Encryptのテストかどうかのフラグ 本番ではfalseにする (指定しないとテスト扱いになる)
      # - CERT_NAME=default # ローカルで認証局を立てるときに使う ※本番ではLet's Encryptから直接取得するのでコメントアウ>トする
      # - HTTPS_METHOD=noredirect # リダイレクトを無効にする # 必要に応じて有効化
    restart: always

networks:
  default:
    external:
      name: bridge
  container-link:
    name: container_network
